services:
  - type: web
    name: sigit-personal
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
